name: letswashlet
description: washlet simulator.
publish_to: 'none'
version: 1.0.8+8

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  # Firebase Analytics
  firebase_core: ^1.17.1
  firebase_analytics: ^9.1.9
  # App Icon
  cupertino_icons: ^1.0.5
  flutter_launcher_icons: ^0.9.3
  # Audio Player
  audioplayers: ^0.20.1
  # Vibration
  vibration: ^1.7.4-nullsafety.0
  # Device Info
  device_info_plus: ^3.2.4
  # Admob
  google_mobile_ads: ^1.2.0
  app_tracking_transparency: ^2.0.2+4
  # Localize
  flutter_localizations:
    sdk: flutter
  intl: ^0.17.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.1
  # App Splash
  flutter_native_splash: ^2.2.3

flutter_icons:
  image_path: "assets/images/icon.png"
  android: true
  ios: true
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "assets/images/appIcon.png"

flutter_native_splash:
  image: "assets/images/icon.png"
  color: "ffffff"

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/images/
    - assets/audios/
  fonts:
    - family: teleIndicators
      fonts:
        - asset: assets/fonts/teleindicadores.ttf
    - family: cornerStone
      fonts:
        - asset: assets/fonts/cornerstone.ttf



